Javascript Tip calculator/app.js
Javascript Tip calculator/index.html

This is my 1st contribution to this repository

JS TIP CACULATOR

---

javaScript Random Quote Generator/index.html
javaScript Random Quote Generator/index.js
javaScript Random Quote Generator/style.css

Random Quote Generator

---

JavaScript Change Background/index.html
JavaScript Change Background/script.js
JavaScript Change Background/style.css

Now multiple colors can be chosen to create a color palette.

Create a color palette

---

Javascript Make Notes/index.html
Javascript Make Notes/index.js

Added JavaScript Project Make-Notes #54

Added JavaScript Project Make-Notes #54

---

blackjackgame/free blackjack.css
blackjackgame/free blackjack.html
blackjackgame/free blackjack.js

this will help to learn the javascript concept by making this game

blackjackgame

---

Javascript Bomberman/README.md
Javascript Bomberman/index.html
Javascript Bomberman/script.js
Javascript Bomberman/styles.css

This project is a javascript based game. It allows you to click a cell from 9*9 grid. It shows the number of bombs placed in the surrounding. If a bomb is clicked at any point, game gets over and you are asked to play again.

Javascript Minesweeper

---

JS_DrawingApp/draw.css
JS_DrawingApp/draw.html
JS_DrawingApp/draw.js

Hello Suraj I have Added Drawing app using JS. This project is good for both beginner's and also good for intermediate who are leaning javascript.

added one awesome javascript project Drawing App

---

Javascript Random Memes Generator/app.js
Javascript Random Memes Generator/index.html
Javascript Random Memes Generator/style.css

In this project, we can generate memes by clicking a button. Whenever we click the button, we can see random memes.

generator-random-memes 

---

Javascript Image-carousel/app.js
Javascript Image-carousel/index.html
Javascript Image-carousel/style.css

I created a project for sliding images. In this project, we can easily slide images by clicking a button.

Add a project name Javascript Image-carousel

---

JavaScript Type Racer/index.js
Javascript Typing Speed test/app.js
Javascript Typing Speed test/index.html
Javascript Typing Speed test/style.css

This is my first PR , hope you like it.

Added Typing Speed Test

---

JavaScript Snake Water Gun Game/index.html
JavaScript Snake Water Gun Game/lol.js

You have 10 chances in game, You play against the computer that will generate the other player, after 10 rounds your result will be displayed i.e the number of draws, wins and loses against the computer, and it will evaluate you based on your performance! Good luck!

Snake Water Gun Game with JS

---

README.md

first line creat  -> create
second line vety -> very

Fixed TYPO in readme.md

---

Guessing-game/index.html
Guessing-game/script.js

Hello,
I have built a guessing app. Kindly review the code and merge the PR
Thanking You!
Happy Coding 👨‍💻

Guessing-game app

---

Java-Script Quiz/app.js
Java-Script Quiz/index.html
Java-Script Quiz/style.css

Please accept my pull request and make valid for Hacktoberfest - 2022

Java Script Quiz Web Application

---

Javascript QR-code maker/app.js
Javascript QR-code maker/index.html
Javascript QR-code maker/style.css

I create a project which makes **QR code** with the help of user input information.

Create a QR-code maker

---

JavaScript Pickle Rick Maze Game/index.html
JavaScript Pickle Rick Maze Game/script.js
JavaScript Pickle Rick Maze Game/style.css

New Game Added!
Please Check my Pull Request and accept it. also add Hecktoberfest label on it.
Thanks & regards 
Abhi Patel

[added] New JavaScript Pickle Rick Maze Game Added

---

QR code Scanner/index.html
QR code Scanner/script.js
QR code Scanner/style.css

Thank you very much for creating this repo and making it available for us!

files added

---

live_chat_app/css/style.css
live_chat_app/index.html
live_chat_app/js/client.js

live chat application

---

RGB Image/index.html
RGB Image/script.js
RGB Image/style.css

Move your mouse and the color will change

Added RGB Image

---

Javascript SuperHero App/index.html
Javascript SuperHero App/script.js
Javascript SuperHero App/style.css

please merge this PR. It took me a lot of efforts to build the entire website from scratch. Also please add the hactoberfest-accepted label.

added a new js project

---

Log in form/index.html
Log in form/style.css

javascript added

---

Calc@hand/project.css
Calc@hand/project.html
Calc@hand/project.js

Added a fully functional calculator at hand.

Added a fully functional calculator

---

Timer App/index.html
Timer App/index.js
Timer App/style.css
Timer App/timer.js

Added stopwatch timer app made in JS. @surajondev kindly add Hacktoberfest tag and merge the PR, thanks!

added stopwatch timer app

---

JavScript Auto Typing Text Animation/Project/index.html
JavScript Auto Typing Text Animation/Project/index.js
JavScript Auto Typing Text Animation/Project/style.css
JavScript Auto Typing Text Animation/README.md

Added Auto text animation using JavaScript and JavaScript Library

---

index.js

You have 100 chances to guess the correct number....Do your best

Added a JAVASCRIPT number game

---

javascript CSS styled calculator/index.html
javascript CSS styled calculator/script.js
javascript CSS styled calculator/style.css

GitHub: @prash240303
**made a js calculator with material UI CSS styled buttons and dark and light mode** 
directory name : javascript CSS styled calculator
new file:   javascript CSS styled calculator/index.html
new file:   javascript CSS styled calculator/script.js
new file:   javascript CSS styled calculator/style.css

contributor name : prashant prabhakar

---

Expense Tracker/Readme.md
Expense Tracker/expense_tracker.css
Expense Tracker/expense_tracker.html
Expense Tracker/expense_tracker.js

This is an Expense Tracker Project made with Html, CSS, JavaScript.

JavaScript Expense Tracker Project

---

Pixel Art Pad/index.html
Pixel Art Pad/index.java

I have built a Pixel Art Pad with HTML and Java, please merge my project under Hacktoberfest.

Pixel Art Pad

---

World Clock/css/style.css
World Clock/index.html
World Clock/js/main.js
World Clock/js/package-lock.json

Added Vanilla JS World clock that displays current time around different time zones.

Added world clock with vanilla JS

---

JavaScript_PasswordGenerator/css/style.css
JavaScript_PasswordGenerator/index.html
JavaScript_PasswordGenerator/js/index.js
JavaScript_PasswordGenerator/readme.md

fix #182 
As discussed, I have upgraded the Password generator project and developed a new UI as well as functionalities for the same

Added Enhanced Password Generator using JS

---

WeatherAPIApp/weather.css
WeatherAPIApp/weatherapp.html
WeatherAPIApp/weatherprog.js

Issue : https://github.com/surajondev/JavaScript/issues/54#event-10677683081
1 . Added a HTML file (weatherapp.html)
2 . Added a CSS file (weather.css)
3 . Added a Javacript file (weatherprog.js)

A New Weather API App
